window.MAISTER_DATA = {
  generated: "2026-07-17T20:02:44Z",
  task: {
    title: "Unify agent projections across supported hosts",
    type: "research",
    status: "completed",
    description: "Design one canonical per-host transformation and invocation contract for all Maister agents.",
    path: ".maister/tasks/research/2026-07-17-unify-agent-projections",
    current_activity: "Research complete; ready for maister:development"
  },
  characteristics: {
    research_type: "mixed",
    supported_hosts: ["codex", "cursor", "kiro-cli"]
  },
  phases: [
    { id: "phase-1", name: "Research foundation", icon_hint: "analysis", status: "completed", started: "2026-07-17T17:38:03Z", completed: "2026-07-17T19:19:39Z", skip_reason: null, summary: "Research recommends one canonical IR, staged projector, exact resolver, and host adapters: Codex injection, Cursor Markdown, Kiro JSON plus prompt.", decisions: [{ decision: "Treat maister-advisor like every other canonical agent.", rationale: "Explicit user constraint." }, { decision: "Use one canonical parser, manifest, and staged projector.", rationale: "Prevents prompt drift and preserves transactional ownership." }, { decision: "Resolve every logical role exactly and fail closed.", rationale: "No fallback may execute another or inline role." }], risks: ["Native discovery and exact invocation still require versioned host probes.", "Kiro requires narrowly scoped multi-root transaction ownership.", "Legacy Codex TOML cleanup must preserve modified or unknown files."], artifacts: [{ path: "planning/research-brief.md", label: "Research brief", html: null }, { path: "planning/research-plan.md", label: "Research plan", html: null }, { path: "planning/sources.md", label: "Source plan", html: null }, { path: "analysis/findings/01-canonical-projection.md", label: "Canonical projection findings", html: null }, { path: "analysis/findings/02-codex-runtime.md", label: "Codex runtime findings", html: null }, { path: "analysis/findings/03-cursor-kiro-runtime.md", label: "Cursor and Kiro runtime findings", html: null }, { path: "analysis/findings/04-installer-tests-docs.md", label: "Installer, tests, and documentation findings", html: null }, { path: "analysis/synthesis.md", label: "Research synthesis", html: null }, { path: "outputs/research-report.md", label: "Research report", html: "outputs/research-report.html" }], gate: { question: "Research foundation complete (initialized, planned, gathered, synthesized). Continue to brainstorming evaluation?", answer: "Continue to brainstorming evaluation", status: "decided" } },
    { id: "phase-2", name: "Evaluate optional phases", icon_hint: "plan", status: "completed", started: "2026-07-17T19:19:39Z", completed: "2026-07-17T19:30:43Z", skip_reason: null, summary: "The user skipped brainstorming and enabled high-level design for the development handoff.", decisions: [{ decision: "Skip brainstorming.", rationale: "Research identified one sufficiently supported architecture without competing alternatives." }, { decision: "Generate high-level design.", rationale: "The architecture spans parsing, projection, installation, dispatch, migration, and verification." }], risks: [], artifacts: [], gate: { question: "Research identifies architectural decisions across parsing, projection, installation, dispatch, migration, and verification, and the design will feed maister:development. Would you like to generate a high-level design?", answer: "Yes, generate design", status: "decided" } },
    { id: "phase-3", name: "Generate solution alternatives", icon_hint: "spec", status: "skipped", started: null, completed: "2026-07-17T19:30:43Z", skip_reason: "Brainstorming disabled by user after research converged on one architecture.", summary: "Skipped because no competing architecture remained after synthesis.", decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-4", name: "Evaluate solution alternatives", icon_hint: "plan", status: "skipped", started: null, completed: "2026-07-17T19:30:43Z", skip_reason: "No generated alternatives to evaluate because brainstorming was skipped.", summary: "The research report recommendation becomes the design direction.", decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-5", name: "Design high-level architecture", icon_hint: "spec", status: "completed", started: "2026-07-17T19:30:43Z", completed: "2026-07-17T19:56:47Z", skip_reason: null, summary: "Portable core with ports and adapters, deterministic staged projections, transactional delivery, and exact fail-closed role dispatch.", decisions: [{ decision: "Keep 28 canonical Markdown roles as the only behavior source.", rationale: "Native host representations are generated from one versioned IR and manifest." }, { decision: "Treat advisor exactly like every other canonical role.", rationale: "No TOML, readonly, sandbox, destination, or adapter exception is permitted." }, { decision: "Use clean installation without legacy Codex TOML migration.", rationale: "The user removed backward-compatibility requirements." }, { decision: "Separate materialization, discovery, and invocation evidence.", rationale: "Structural parity does not prove exact execution." }], risks: ["Codex spawn/model control remains version-dependent.", "Cursor precedence and Kiro exact identity require native probes.", "Kiro multi-root delivery needs complete rollback and race coverage."], artifacts: [{ path: "outputs/high-level-design.md", label: "High-level design", html: "outputs/high-level-design.html" }, { path: "outputs/decision-log.md", label: "Decision log", html: "outputs/decision-log.html" }], gate: { question: "Design complete. Continue to output generation?", answer: "Continue to output generation", status: "decided" } },
    { id: "phase-6", name: "Summarize research and hand off", icon_hint: "done", status: "completed", started: "2026-07-17T19:56:47Z", completed: "2026-07-17T20:02:44Z", skip_reason: null, summary: "Final research summary and development handoff generated and approved by the user.", decisions: [{ decision: "Use the high-level design and decision log as the authoritative implementation input.", rationale: "They include the clean-install correction and supersede the earlier migration recommendation." }], risks: ["Native discovery and exact invocation remain unavailable until versioned host probes pass."], artifacts: [{ path: "outputs/decision-summary.md", label: "Decision summary", html: "outputs/decision-summary.html" }], gate: { question: "Research summary and development handoff are complete. Complete the workflow?", answer: "Complete workflow", status: "decided" } }
  ],
  verification: { status: null, issues: [], fixes: [], reverify_count: 0 },
  gate_history: [{ idempotency_key: "sha256:8dc80ac772693c815f0dfac96f7baa45a3cded3e406f16c6f5a42756f1e157d4", phase_id: "phase-1", gate_type: "phase-1-exit", status: "decided", question: "Research foundation complete (initialized, planned, gathered, synthesized). Continue to brainstorming evaluation?", selected_option: "Continue to brainstorming evaluation", final_actor: "user" }, { idempotency_key: "sha256:99f3113cd7105936bc727db4bf0cb86d5ef197d114aaaaf2278ad15e56713dac", phase_id: "phase-2", gate_type: "optional-phase-selection", status: "decided", question: "Research converged on one architecture and did not identify competing alternatives, so brainstorming is unlikely to add value. Would you like to explore solution alternatives?", selected_option: "No, skip brainstorming", final_actor: "user" }, { idempotency_key: "sha256:9b2ddc4d107ba91823dbe96461fee0cf7e83bbc3e977a797aa6c644d34c3cf89", phase_id: "phase-2", gate_type: "optional-phase-selection", status: "decided", question: "Research identifies architectural decisions across parsing, projection, installation, dispatch, migration, and verification, and the design will feed maister:development. Would you like to generate a high-level design?", selected_option: "Yes, generate design", final_actor: "user" }, { idempotency_key: "sha256:08d897407996d017ff889aaf062a92e49e6cd9aa9d9cd5942601cd8ea1002e91", phase_id: "phase-5", gate_type: "research-clarification", status: "decided", question: "Proposed design assumptions: 28 canonical Markdown roles remain the only behavior source; Codex uses generic subagent prompt injection; Cursor and Kiro receive deterministic native projections; role resolution is exact and fail-closed; legacy Codex TOML cleanup is hash-gated and preserves modified files. Confirm these assumptions?", selected_option: "Correct assumptions", final_actor: "user" }, { idempotency_key: "sha256:6bdf08499f5ea52adcb109887df08612b87fed5c1a2a6ba779d4fc70c9cb160e", phase_id: "phase-5", gate_type: "phase-5-exit", status: "decided", question: "Design complete. Continue to output generation?", selected_option: "Continue to output generation", final_actor: "user" }, { idempotency_key: "sha256:d80f674bb46ee9bc4ab3f4827a639076174888b935b69a4d0c8ad83216fb4ee0", phase_id: "phase-6", gate_type: "final-handoff-approval", status: "decided", question: "Research summary and development handoff are complete. Complete the workflow?", selected_option: "Complete workflow", final_actor: "user" }]
};
