window.MAISTER_DATA = {
  generated: "2026-07-13T16:16:12Z",
  task: {
    title: "Issue tracker workflow for Maister",
    type: "research",
    status: "completed",
    description: "Research selectable issue trackers, fast task capture, and issue-to-workflow handoff.",
    path: ".maister/tasks/research/2026-07-13-issue-tracker-workflow",
    current_activity: null
  },
  characteristics: { research_type: "mixed" },
  phases: [
    { id: "phase-1", name: "Research foundation", icon_hint: "analysis", status: "completed", started: "2026-07-13T13:53:40Z", completed: "2026-07-13T14:38:08Z", skip_reason: null, summary: "Research recommends an executable provider helper plus declarative capabilities, with Local Markdown and GitHub in v1 and immutable snapshots handed into workflows.", decisions: [{ decision: "Wybrać helper wykonywalny + deklaratywne capabilities, nie prose-as-provider-API.", rationale: "Zapewnia jeden walidowany kontrakt i ogranicza różnice między hostami." }, { decision: "Utrwalać maister-issue://...; przyjmować krótsze aliasy wyłącznie, gdy rozstrzygają się jednoznacznie.", rationale: "Referencje pozostają stabilne między providerami." }, { decision: "Rozwiązać i zsnapshotować issue przed utworzeniem workflow state; późniejszy drift tylko sygnalizować.", rationale: "Workflow pozostaje odtwarzalny, a tracker zachowuje żywy backlog." }, { decision: "W v1 wdrożyć Local Markdown i GitHub; zostawić GitLab/Jira/Linear bez pustych stubów.", rationale: "Ogranicza zakres i respektuje minimalną implementację." }], risks: ["Sprzeczny schemat orchestrator-state.yml blokuje wybór jednego kanonicznego miejsca dla source_issue.", "quick-plan ma różną trwałość na hostach; wspólny artifact proweniencji wymaga decyzji produktowej.", "Zakres mutacji trackera w v1 nie jest zatwierdzony.", "Local locks/atomic replace wymagają jasno zadeklarowanego wsparcia zwykłych lokalnych filesystemów."], artifacts: [{ path: "planning/research-brief.md", label: "Research Brief", html: null }, { path: "planning/research-plan.md", label: "Research Plan", html: null }, { path: "planning/sources.md", label: "Source Register", html: null }, { path: "analysis/findings/01-maister-internals.md", label: "Maister Internals", html: null }, { path: "analysis/findings/02-mattpocock-skills.md", label: "mattpocock/skills Prior Art", html: null }, { path: "analysis/findings/03-tracker-providers.md", label: "Tracker Provider Contracts", html: null }, { path: "analysis/findings/04-product-quality-tradeoffs.md", label: "Product Quality Trade-offs", html: null }, { path: "analysis/synthesis.md", label: "Research Synthesis", html: null }, { path: "outputs/research-report.md", label: "Research Report", html: "outputs/research-report.html" }, { path: "outputs/decision-summary.md", label: "Decision Summary", html: "outputs/decision-summary.html" }], gate: { question: "Research foundation complete (initialized, planned, gathered, synthesized). Continue to brainstorming evaluation?", answer: "Pause workflow", status: "decided" } },
    { id: "phase-2", name: "Evaluate brainstorming value", icon_hint: "plan", status: "completed", started: "2026-07-13T14:59:02Z", completed: "2026-07-13T15:05:17Z", skip_reason: null, summary: "Brainstorming and high-level design were both enabled after advisor-backed recommendations.", decisions: [{ decision: "Enable brainstorming", rationale: "The user accepted the advisor-backed recommendation to explore material architectural trade-offs." }, { decision: "Enable high-level design", rationale: "The user authorized following the advisor when it confirms the original recommendation." }], risks: [], artifacts: [], gate: { question: "The research identifies architectural decisions that would directly feed development. Would you like to generate a high-level design?", answer: "Yes, generate design", status: "decided" } },
    { id: "phase-3", name: "Generate solution alternatives", icon_hint: "spec", status: "completed", started: "2026-07-13T15:05:17Z", completed: "2026-07-13T15:17:32Z", skip_reason: null, summary: "Six sequential decision areas compare 18 alternatives and recommend an executable helper, root provenance, durable plans, capture-only mutations, transactional Local Markdown, and Local-first delivery.", decisions: [{ decision: "Executable Node ESM helper + CapabilitySet", rationale: "Host parity, fail-closed validation, and testability." }, { decision: "Root source_issue + immutable snapshot", rationale: "Separates live tracker ownership from reproducible workflow input." }, { decision: "Durable cross-host quick-plan artifact", rationale: "Creates one canonical handoff." }, { decision: "Capture-only v1 mutations", rationale: "Keeps handoff read-only and bounds risk." }, { decision: "Local Markdown first, GitHub second", rationale: "Stabilizes the conformance contract before hosted integration." }], risks: ["State schema variants must be unified before source_issue.", "Local transaction assumptions exclude network filesystems.", "GitHub timeout after dispatch can be an ambiguous commit.", "Durable quick-plan needs cross-host parity tests."], artifacts: [{ path: "outputs/solution-exploration.md", label: "Solution Exploration", html: "outputs/solution-exploration.html" }], gate: { question: "Continue to solution convergence?", answer: "Continue to solution convergence", status: "decided" } },
    { id: "phase-4", name: "Evaluate brainstorming alternatives", icon_hint: "plan", status: "completed", started: "2026-07-13T15:17:32Z", completed: "2026-07-13T15:51:06Z", skip_reason: null, summary: "All six convergence areas are resolved into an incremental provider architecture; the workflow is paused before high-level design.", decisions: [{ decision: "Choose a small Node ESM helper with exact JSON and a declarative CapabilitySet.", rationale: "It provides the strongest host parity, fail-closed validation, and testability." }, { decision: "Anchor source_issue at the root of orchestrator-state.yml after schema unification.", rationale: "It preserves one resume and audit source of truth." }, { decision: "Persist quick-plan in .maister/plans/*.md on every host.", rationale: "It provides a portable, Git-reviewable handoff." }, { decision: "Limit v1 mutations to explicit capture/create.", rationale: "It bounds side effects and keeps handoff and resume read-only." }, { decision: "Use UUID records, per-record locks, CAS, and atomic replace for Local Markdown.", rationale: "It prevents lost updates while preserving readable files." }, { decision: "Deliver Local Markdown first and GitHub second.", rationale: "It creates small verifiable increments over one conformance contract." }], risks: ["Codex fully_automatic remains unsupported because the host-native adapter/E2E is absent and the workflow state schema diverges from the runner contract."], artifacts: [{ path: "analysis/codex-fully-automatic-diagnosis.md", label: "Codex Fully Automatic Diagnosis", html: null }], gate: { question: "Brainstorming complete. Continue to high-level design?", answer: "Pause workflow", status: "decided" } },
    { id: "phase-5", name: "Design high-level architecture", icon_hint: "spec", status: "completed", started: "2026-07-13T15:55:19Z", completed: "2026-07-13T16:11:56Z", skip_reason: null, summary: "A layered provider boundary with immutable handoff snapshots separates live tracker ownership from reproducible workflow input; six ADRs make the design development-ready.", decisions: [{ decision: "Use one executable provider boundary instead of prose-only adapters or a command-template DSL.", rationale: "This centralizes validation, redaction, and cross-host semantics (ADR-001)." }, { decision: "Keep tracker data and workflow execution state under separate ownership, with root source_issue provenance after state-schema unification.", rationale: "This preserves tracker and workflow authority boundaries (ADR-002)." }, { decision: "Persist quick plans as portable Markdown artifacts on every host and treat native plan UI as a projection.", rationale: "This produces one durable cross-host handoff (ADR-003)." }, { decision: "Limit v1 mutations to explicit capture/create; handoff, resume, and drift checks remain read-only.", rationale: "This bounds side effects and operational risk (ADR-004)." }, { decision: "Give Local Markdown per-UUID records, per-record locks, compare-and-swap, and atomic replace only on ordinary local filesystems.", rationale: "This prevents lost updates within the supported filesystem boundary (ADR-005)." }, { decision: "Deliver Local Markdown first and GitHub second under the same conformance contract.", rationale: "This stabilizes the provider seam incrementally (ADR-006)." }], risks: ["The competing workflow-state schemas must be unified and fixture-tested before adding the root source_issue field; dual-read behavior is not part of this design.", "Local filesystem guarantees do not extend to network or distributed filesystems; unsupported environments must fail preflight with an actionable diagnostic.", "A GitHub create timeout after dispatch may remain ambiguous_commit; v1 must not blindly retry or switch transport.", "Cross-host fixtures must prove that canonical quick-plan content and native UI projections cannot silently diverge.", "Fully automatic Codex continuation remains unsupported until a host-native adapter, unified state schema, and end-to-end verification exist."], artifacts: [{ path: "outputs/high-level-design.md", label: "High-Level Design", html: "outputs/high-level-design.html" }, { path: "outputs/decision-log.md", label: "Decision Log", html: "outputs/decision-log.html" }], gate: { question: "Design complete. Continue to output generation?", answer: "Continue to output generation", status: "decided" } },
    { id: "phase-6", name: "Summarize research and suggest next steps", icon_hint: "done", status: "completed", started: "2026-07-13T16:11:56Z", completed: "2026-07-13T16:16:12Z", skip_reason: null, summary: "The complete research package is approved for final handoff, with five linked deliverables and the remaining prerequisites preserved.", decisions: [], risks: ["Workflow-state schema unification remains a prerequisite for root source_issue provenance.", "Codex automatic continuation remains unsupported until host-native end-to-end validation passes."], artifacts: [{ path: "outputs/research-report.md", label: "Research Report", html: "outputs/research-report.html" }, { path: "outputs/solution-exploration.md", label: "Solution Exploration", html: "outputs/solution-exploration.html" }, { path: "outputs/high-level-design.md", label: "High-Level Design", html: "outputs/high-level-design.html" }, { path: "outputs/decision-log.md", label: "Decision Log", html: "outputs/decision-log.html" }, { path: "outputs/decision-summary.md", label: "Decision Summary", html: "outputs/decision-summary.html" }], gate: { question: "Research outputs are complete. Approve the final handoff?", answer: "Complete workflow", status: "decided" } }
  ],
  verification: { status: null, issues: [], fixes: [], reverify_count: 0 },
  gate_history: [
    { idempotency_key: "sha256:8dc80ac772693c815f0dfac96f7baa45a3cded3e406f16c6f5a42756f1e157d4", phase_id: "phase-1", gate_type: "phase-1-exit", status: "decided", question: "Research foundation complete (initialized, planned, gathered, synthesized). Continue to brainstorming evaluation?", selected_option: "Pause workflow", final_actor: "user", rationale: "User explicitly chose to pause after reviewing the completed research foundation.", confidence: "high", user_override: true },
    { idempotency_key: "sha256:ef97f9b46a7c28e4c418e8abf667877f80fd953dacc6d142349fdfd47b1e72e6", phase_id: "phase-2", gate_type: "optional-phase-selection", status: "decided", question: "Multiple viable architectures and competing trade-offs make brainstorming valuable. Would you like to explore solution alternatives?", selected_option: "Yes, explore alternatives", final_actor: "user", rationale: "User accepted the recommendation to explore alternatives because the research contains material competing architectural trade-offs.", confidence: "high", user_override: false },
    { idempotency_key: "sha256:571789075d8fe42ced95941597dca774808f00995f22ba6b6bf6ea6a477cf575", phase_id: "phase-2", gate_type: "optional-phase-selection", status: "decided", question: "The research identifies architectural decisions that would directly feed development. Would you like to generate a high-level design?", selected_option: "Yes, generate design", final_actor: "user", rationale: "User authorized following advisor recommendations that agree with the original recommendation, confirming generation of the high-level design.", confidence: "high", user_override: false },
    { idempotency_key: "sha256:b44cce49b270e039db9825c224697b82b1f7ac236d4a1a361cd36e21a6e3cd13", phase_id: "phase-3", gate_type: "phase-3-exit", status: "decided", question: "Continue to solution convergence?", selected_option: "Continue to solution convergence", final_actor: "user", rationale: "User chose to continue from solution generation to sequential convergence.", confidence: "high", user_override: false },
    { idempotency_key: "sha256:8b8e6268eadeea8e9075d04f18884ea11c39055775dd1d52df2849b6bd0c2af6", phase_id: "phase-4", gate_type: "research-convergence", status: "decided", question: "Which provider execution boundary should Maister use?", selected_option: "1C — mały helper Node ESM i deklaratywny CapabilitySet (Recommended)", final_actor: "user", rationale: "User selected the executable Node ESM helper and declarative CapabilitySet as the shared provider execution boundary.", confidence: "high", user_override: false },
    { idempotency_key: "sha256:1405b0df3ba973ffe77cf109cf542cc3b69b3d0c709d74780c3d6c6c2206be62", phase_id: "phase-4", gate_type: "research-convergence", status: "decided", question: "Where should canonical source_issue provenance be anchored?", selected_option: "2A — korzeniowy source_issue w orchestrator-state.yml (Recommended)", final_actor: "user", rationale: "User selected a root source_issue provenance pointer in orchestrator-state.yml after schema unification.", confidence: "high", user_override: false },
    { idempotency_key: "sha256:6420d393ee515436120df4c9fc4ee3237a536c22f59202bc3af214652b88006b", phase_id: "phase-4", gate_type: "research-convergence", status: "decided", question: "How should quick-plan provenance persist across hosts?", selected_option: "3B — wspólny .maister/plans/*.md plus native UI (Recommended)", final_actor: "user", rationale: "User selected a durable cross-host quick-plan artifact with native UI as a projection.", confidence: "high", user_override: false },
    { idempotency_key: "sha256:2d424dd21881954ddefce454a09a7a06999e6b8804b6a11a5464d25f1abcaad2", phase_id: "phase-4", gate_type: "research-convergence", status: "decided", question: "Which tracker mutation surface should v1 expose?", selected_option: "4A — tylko jawne capture/create (Recommended)", final_actor: "user", rationale: "User limited v1 tracker mutations to explicit capture/create.", confidence: "high", user_override: false },
    { idempotency_key: "sha256:eaaf8832a0e880c6b34925b886e016307a54722d2672df5fd5e37f6ee2f43863", phase_id: "phase-4", gate_type: "research-convergence", status: "decided", question: "Which persistence protocol should Local Markdown use?", selected_option: "5A — rekord per UUID, per-record lock, CAS i atomic replace (Recommended)", final_actor: "user", rationale: "User selected UUID records with per-record locks, CAS, and atomic replace.", confidence: "high", user_override: false },
    { idempotency_key: "sha256:2e2af5cd201403e231f02eb0b77f59014f873fb8d3539b80647f50fb1615a7f6", phase_id: "phase-4", gate_type: "research-convergence", status: "decided", question: "In what order should v1 deliver tracker providers?", selected_option: "6B — Local Markdown tracer, następnie GitHub (Recommended)", final_actor: "user", rationale: "User selected Local Markdown first and GitHub second over the same conformance contract.", confidence: "high", user_override: false },
    { idempotency_key: "sha256:deff7dc9407e4bf7bd8e9827eea83f0943d11d5daa1793b43db636eb584db001", phase_id: "phase-4", gate_type: "phase-4-exit", status: "decided", question: "Brainstorming complete. Continue to high-level design?", selected_option: "Pause workflow", final_actor: "user", rationale: "User chose to pause after completing all six convergence decisions and before high-level design.", confidence: "high", user_override: true },
    { idempotency_key: "sha256:d2d155b8dc6dc759724bbddbe3f5de77683741a654c0091310ef6e2f95fa31d6", phase_id: "phase-5", gate_type: "research-clarification", status: "decided", question: "The six convergence decisions establish the design direction. Should the high-level design proceed with those assumptions unchanged?", selected_option: "Confirm assumptions", final_actor: "user", rationale: "User confirmed that the high-level design should proceed with the six converged assumptions unchanged.", confidence: "high", user_override: false },
    { idempotency_key: "sha256:6bdf08499f5ea52adcb109887df08612b87fed5c1a2a6ba779d4fc70c9cb160e", phase_id: "phase-5", gate_type: "phase-5-exit", status: "decided", question: "Design complete. Continue to output generation?", selected_option: "Continue to output generation", final_actor: "user", rationale: "User chose to continue from the verified high-level design to final output generation.", confidence: "high", user_override: false },
    { idempotency_key: "sha256:283ebe0a6247edeaaddef3b7647f654d966aa190da4ee71b2f961b3dd18d2825", phase_id: "phase-6", gate_type: "final-handoff-approval", status: "decided", question: "Research outputs are complete. Approve the final handoff?", selected_option: "Complete workflow", final_actor: "user", rationale: "User approved the final research handoff and completion of the workflow.", confidence: "high", user_override: false }
  ]
};
