window.MAISTER_DATA = {
  generated: "2026-07-20T19:58:03Z",
  task: {
    title: "Add GitHub-only npm-exec distribution for Maister",
    type: "development",
    status: "completed",
    description: "Run the launcher from an exact GitHub tag or commit, support private repositories through GitHub authentication, and publish nothing to npmjs or another package registry.",
    path: ".maister/tasks/development/2026-07-19-npx-release-distribution",
    current_activity: "Workflow complete"
  },
  active_gate: null,
  characteristics: {
    has_reproducible_defect: true,
    modifies_existing_code: true,
    creates_new_entities: true,
    involves_data_operations: true,
    ui_heavy: false
  },
  phases: [
    { id: "phase-1", name: "Analyze codebase & clarify requirements", icon_hint: "analysis", status: "completed", started: "2026-07-19T12:22:35Z", completed: "2026-07-19T17:07:33Z", skip_reason: null, summary: "The existing release and transactional installer foundations are reusable.", decisions: [], risks: [], artifacts: [{ path: "analysis/codebase-analysis.md", label: "Codebase analysis", html: null }], gate: { question: "Continue to Phase 2?", answer: "Continue to Phase 2", status: "decided" } },
    { id: "phase-2", name: "Analyze gaps & clarify scope", icon_hint: "analysis", status: "completed", started: "2026-07-19T23:21:25Z", completed: "2026-07-19T23:48:05Z", skip_reason: null, summary: "GitHub-only scope is fully analyzed and all architecture decisions are resolved; routing to TDD Red was approved.", decisions: [{ decision: "Remove npm registry publication.", rationale: "The user requires all distribution to remain on GitHub and the repository may be private." }, { decision: "Keep tar@7.5.20 as a normal dependency.", rationale: "Maister remains GitHub-only while npmjs may serve the vetted third-party dependency." }, { decision: "Use environment tokens, then gh auth, then anonymous access.", rationale: "Private interactive users can reuse GitHub CLI authentication while public access emits no credentials." }, { decision: "Disable workflow advisors.", rationale: "The user explicitly requested direct responses without an advisor." }], risks: ["The selected gh auth fallback must keep tokens out of argv, URLs, diagnostics, and evidence.", "The previous aggregate transaction, abrupt-crash, and archive-memory evidence remains incomplete."], artifacts: [{ path: "analysis/gap-analysis.md", label: "Gap analysis", html: null }, { path: "analysis/scope-clarifications.md", label: "Scope decisions", html: null }], gate: { question: "Continue to Phase 3: TDD Red Gate?", answer: "Continue to Phase 3: TDD Red Gate", status: "decided" } },
    { id: "phase-3", name: "Write failing test (TDD Red)", icon_hint: "verify", status: "completed", started: "2026-07-19T23:48:05Z", completed: "2026-07-20T07:54:55Z", skip_reason: null, summary: "Three focused tests fail against the current implementation, proving the GitHub-only contract defects.", decisions: [{ decision: "Keep registry publication, credential precedence, and private asset transport in one focused red contract suite.", rationale: "These are independent observable defects in the revised GitHub-only scope." }, { decision: "Stop transport tests before extraction or delegation.", rationale: "URL and credential behavior can be reproduced without mutating host state." }], risks: ["The bounded non-shell gh auth fallback still needs an injectable command boundary and dedicated implementation tests.", "Aggregate transaction, crash recovery, multi-journal recovery, and archive-memory evidence remain downstream verification obligations."], artifacts: [{ path: "implementation/tdd-red-gate.md", label: "TDD red gate", html: null }, { path: "../../../tests/platform-independent/launcher-github-only.test.mjs", label: "Failing GitHub-only contract test", html: null }], gate: { question: "TDD red gate complete. Continue to Phase 4?", answer: "Continue to Phase 4", status: "decided" } },
    { id: "phase-4", name: "Generate UI mockups", icon_hint: "spec", status: "skipped", started: "2026-07-20T07:54:55Z", completed: "2026-07-20T08:35:31Z", skip_reason: "Task characteristic ui_heavy is false; no UI mockups are required.", summary: "UI mockup generation was skipped because the task has no user-interface surface.", decisions: [], risks: [], artifacts: [], gate: { question: "UI mockups complete. Continue to Phase 5?", answer: "Continue to Phase 5", status: "decided" } },
    { id: "phase-5", name: "Gather requirements & create specification", icon_hint: "spec", status: "completed", started: "2026-07-20T08:35:31Z", completed: "2026-07-20T09:03:48Z", skip_reason: null, summary: "The rewritten specification defines 38 Must requirements and fully supersedes public-npm publication with exact GitHub tag/commit distribution.", decisions: [{ decision: "Supersede every historical public-npm publication assumption.", rationale: "npm is only the local Git-package client and may read dependencies; GitHub is the only Maister distribution surface." }, { decision: "Make all 38 requirements release-blocking.", rationale: "Identity, transport, transaction, recovery, memory, and no-registry evidence jointly define safe distribution." }], risks: ["The implementation is not releasable until aggregate transactions, crash/journal recovery, bounded memory, public/private smokes, and zero registry mutation are proven."], artifacts: [{ path: "analysis/requirements.md", label: "Requirements", html: null }, { path: "analysis/technical-clarifications.md", label: "Technical clarifications", html: null }, { path: "implementation/spec.md", label: "Implementation specification", html: "implementation/spec.html" }], gate: { question: "Continue to specification audit?", answer: "Continue to specification audit", status: "decided" } },
    { id: "phase-6", name: "Audit specification", icon_hint: "verify", status: "completed", started: "2026-07-20T09:03:48Z", completed: "2026-07-20T09:57:16Z", skip_reason: null, summary: "Independent re-audit passed with zero findings; all 38 Must requirements match exactly across Markdown and HTML.", decisions: [{ decision: "Accept the remediated specification as implementation-ready.", rationale: "Independent mechanical and semantic checks found no remaining blocker, important issue, advisory, or hidden decision." }], risks: ["Implementation must still produce every release-blocking evidence item defined by the specification."], artifacts: [{ path: "verification/spec-audit.md", label: "Specification audit", html: null }, { path: "analysis/spec-fix-decisions.md", label: "Resolved audit remediation", html: null }], gate: { question: "Continue to implementation planning?", answer: "Continue to implementation planning", status: "decided" } },
    { id: "phase-7", name: "Plan implementation", icon_hint: "plan", status: "completed", started: "2026-07-20T09:57:16Z", completed: "2026-07-20T10:17:52Z", skip_reason: null, summary: "Nine disjoint groups cover all 38 Must requirements through 55 executable steps, exact tests, recovery rules, and a ten-item approval scope.", decisions: [{ decision: "Execute nine disjoint implementation groups across six dependency waves.", rationale: "This preserves single-writer ownership while allowing safe parallel waves." }, { decision: "Keep the existing three-case TDD red gate unchanged until production turns it green.", rationale: "The focused failures remain direct defect evidence." }, { decision: "Treat public E2E, hermetic private transport, aggregate/crash/RSS evidence, and zero registry mutation as release gates.", rationale: "They are binding audited requirements." }], risks: ["Protected tag configuration and a published exact candidate Release are external prerequisites; missing evidence blocks the release.", "Streaming memory, crash boundaries, multi-journal isolation, and three-OS transactions remain high-risk gates."], artifacts: [{ path: "implementation/implementation-plan.md", label: "Implementation plan", html: "implementation/implementation-plan.html" }], gate: { question: "Continue to implementation approval?", answer: "Continue to implementation approval", status: "decided" } },
    { id: "phase-8", name: "Execute implementation", icon_hint: "code", status: "completed", started: "2026-07-20T10:22:06Z", completed: "2026-07-20T12:38:25Z", skip_reason: null, summary: "All nine groups and 55 implementation steps are complete; local, aggregate, crash, package, policy, and clean-parity gates pass.", decisions: [{ decision: "Keep GitHub as the only Maister distribution surface.", rationale: "The package is private and release automation has no registry mutation path." }, { decision: "Block real public smoke until the exact canonical tag and Release exist.", rationale: "The repository currently returns no v2.2.1 tag and a 404 exact Release; fixtures or another repository cannot substitute." }], risks: ["Real public smoke remains unavailable until v2.2.1 and its exact GitHub Release assets are published through the protected workflow."], artifacts: [{ path: "implementation/implementation-plan.md", label: "Implementation plan", html: "implementation/implementation-plan.html" }, { path: "implementation/work-log.md", label: "Work log", html: null }], gate: { question: "Continue to verification?", answer: "Continue to verification", status: "decided" } },
    { id: "phase-9", name: "Verify test passes (TDD Green)", icon_hint: "verify", status: "completed", started: "2026-07-20T12:38:25Z", completed: "2026-07-20T12:51:41Z", skip_reason: null, summary: "The unchanged focused GitHub-only contract suite now passes 3/3.", decisions: [{ decision: "Preserve the original three-case test without weakening its assertions.", rationale: "The green result must prove the Phase 3 defects were fixed rather than hidden." }], risks: ["The real anonymous public exact-selector smoke remains unavailable until the canonical v2.2.1 tag and GitHub Release assets exist."], artifacts: [{ path: "implementation/tdd-green-gate.md", label: "TDD green gate", html: null }, { path: "../../../tests/platform-independent/launcher-github-only.test.mjs", label: "Passing GitHub-only contract test", html: null }], gate: { question: "TDD gate passed. Continue to Phase 10?", answer: "Continue to Phase 10", status: "decided" } },
    { id: "phase-10", name: "Prompt verification options", icon_hint: "verify", status: "completed", started: "2026-07-20T12:51:41Z", completed: "2026-07-20T13:01:44Z", skip_reason: null, summary: "All four recommended standard verifications and user documentation are selected; E2E remains disabled for this non-browser task.", decisions: [{ decision: "Run code review, pragmatic review, reality check, and production readiness.", rationale: "The user selected the complete recommended verification matrix." }, { decision: "Generate user documentation.", rationale: "The user accepted the recommended documentation phase." }], risks: [], artifacts: [], gate: { question: "Generate user documentation?", answer: "Yes (Recommended)", status: "decided" } },
    { id: "phase-11", name: "Verify implementation & resolve issues", icon_hint: "verify", status: "completed", started: "2026-07-20T13:01:44Z", completed: "2026-07-20T19:40:29Z", skip_reason: null, summary: "Source-controlled implementation passes the current local verification gates: direct platform-independent exit 0 and focused policy/guard 16/16. V-007/V-008 remain external; the user approved continuation with known issues.", decisions: [{ decision: "Fix V-016 through a downstream final evidence job.", rationale: "All three public no-auth smokes precede hermetic transport and final evidence upload." }, { decision: "Fix CQ-102 and subsequent release-harness findings.", rationale: "Checkout credentials, CI coverage, redirect, ambient transport, and diagnostic boundaries are now guarded before public acquisition." }, { decision: "Keep publication blocked.", rationale: "The exact public v2.2.1 Release/protected run and required repository protections remain unavailable." }, { decision: "Proceed with known issues.", rationale: "The user authorized workflow continuation while preserving the external release NO-GO." }], risks: ["The canonical repository has no remote v2.2.1 tag or exact GitHub Release.", "Required GitHub protection controls are external administrative prerequisites."], artifacts: [{ path: "verification/implementation-verification.md", label: "Implementation verification", html: "verification/implementation-verification.html" }, { path: "verification/test-suite-results.md", label: "Test suite results", html: null }, { path: "verification/completeness-check.md", label: "Completeness check", html: null }, { path: "verification/code-review-report.md", label: "Code review", html: null }, { path: "verification/pragmatic-review.md", label: "Pragmatic review", html: null }, { path: "verification/production-readiness-report.md", label: "Production readiness", html: null }, { path: "verification/reality-check.md", label: "Reality check", html: null }], gate: { question: "Continue to Phase 12?", answer: "Continue to Phase 12", status: "decided" } },
    { id: "phase-12", name: "Run E2E tests", icon_hint: "verify", status: "skipped", started: "2026-07-20T19:40:29Z", completed: "2026-07-20T19:40:29Z", skip_reason: "options.e2e_enabled is false; E2E browser verification is disabled for this non-browser task.", summary: "E2E browser verification was skipped because this non-browser task has e2e_enabled set to false.", decisions: [], risks: [], artifacts: [], gate: { question: "E2E complete. Continue to Phase 13?", answer: "Continue to Phase 13", status: "decided" } },
    { id: "phase-13", name: "Generate user documentation", icon_hint: "docs", status: "completed", started: "2026-07-20T19:44:26Z", completed: "2026-07-20T19:50:09Z", skip_reason: null, summary: "Generated the GitHub-only user guide with exact tag/full-commit install and npm exec examples, public/private credential boundaries, provenance and recovery guidance, supported Codex/Cursor/Kiro targets, current external blockers, and the future-private migration checklist.", decisions: [{ decision: "Document direct GitHub package acquisition without npm publication.", rationale: "The approved distribution policy keeps Maister on GitHub and uses npm only as the local Git-package client and read-only dependency resolver." }, { decision: "Document the future private-repository path without creating another repository.", rationale: "The user requested a durable checklist for a possible later visibility change while preserving the current canonical repository." }], risks: ["The examples use the approved v2.2.1 selector contract, but the canonical public v2.2.1 Release is still an external prerequisite and is explicitly described as unavailable."], artifacts: [{ path: "documentation/user-guide.md", label: "GitHub-only user guide", html: null }], gate: { question: "Documentation complete. Continue to Phase 14?", answer: "Continue to Phase 14", status: "decided" } },
    { id: "phase-14", name: "Finalize workflow", icon_hint: "done", status: "completed", started: "2026-07-20T19:54:48Z", completed: "2026-07-20T19:58:03Z", skip_reason: null, summary: "Workflow completed after explicit final-handoff approval. Source-controlled implementation is locally verified; release acceptance remains NO-GO for external V-007/V-008.", decisions: [{ decision: "Complete workflow.", rationale: "The user explicitly approved final handoff after all enabled phases and reports were persisted." }], risks: ["Canonical v2.2.1 Release and required GitHub protections remain external blockers."], artifacts: [{ path: "outputs/decision-summary.md", label: "Decision summary", html: "outputs/decision-summary.html" }, { path: "outputs/decision-summary.html", label: "Decision summary HTML", html: null }], gate: { question: "Complete workflow?", answer: "Complete workflow", status: "decided" } }
  ],
  verification: {
    status: "failed",
    issues: [
      { severity: "critical", category: "anonymous-smoke", description: "CQ-102 public-smoke disables checkout credentials and rejects local Git auth residue before acquisition; locally reverified.", fixable: true, fixed: true },
      { severity: "critical", category: "workflow-order", description: "V-016 writes hermetic-private verification before public no-auth smoke and omits PUBLIC_NO_AUTH_SMOKE_VERIFIED.", fixable: true, fixed: true },
      { severity: "critical", category: "identity", description: "Runtime Release-tag target is not independently resolved.", fixable: true, fixed: true },
      { severity: "critical", category: "archive", description: "Hostile-archive rejection has an unhandled-rejection race.", fixable: true, fixed: true },
      { severity: "critical", category: "workflow", description: "Release CI dirties its checkout before strict parity.", fixable: true, fixed: true },
      { severity: "critical", category: "documentation", description: "Task user guide still describes registry npm.", fixable: true, fixed: true },
      { severity: "critical", category: "evidence", description: "Public-smoke evidence record and three-OS npm-major coverage are incomplete.", fixable: true, fixed: true },
      { severity: "critical", category: "release", description: "Real public v2.2.1 and protected GitHub evidence are unavailable.", fixable: false, fixed: false },
      { severity: "critical", category: "repository-controls", description: "Required GitHub tag, branch, and environment protections are not observable.", fixable: false, fixed: false },
      { severity: "warning", category: "resilience", description: "Aggregate watchdog, signal semantics, output bounds, and behavioral recovery/platform oracles need hardening.", fixable: true, fixed: true }
    ],
    fixes: [
      "Resolved and peeled exact Release tag references.",
      "Supervised archive stream failures and bounded delegated output with backpressure.",
      "Moved strict parity before prepare and pinned the protected three-OS workflow toolchain.",
      "Completed exact-selector public-smoke identity and lifecycle evidence.",
      "Restored exact recovery modes and expanded crash, journal, and platform oracles.",
      "Added a terminal external aggregate watchdog that preserves final-tree evidence.",
      "Rewrote GitHub-only usage and future-private migration documentation."
      ,"Finalized lifecycle evidence only after complete three-OS public no-auth smoke and subsequent hermetic private transport verification."
      ,"Disabled public-smoke checkout credential persistence and added a redacting fail-closed Git auth residue guard before acquisition."
      ,"Covered release-critical harness files in CI filters and release validation; manually bounded redirects; cleared ambient transport variables; and removed raw child diagnostics."
    ],
    reverify_count: 3
  },
  gate_history: [
    { phase_id: "phase-14", gate_type: "final-handoff-approval", question: "Complete workflow?", answer: "Keep workflow open", status: "decided" },
    { phase_id: "phase-2", gate_type: "scope-expansion", question: "Replace public npmjs distribution with GitHub-only distribution?", answer: "Use GitHub-only distribution and remove npm registry publication", status: "decided" },
    { phase_id: "phase-2", gate_type: "phase-2-scope-decision", question: "Which archive dependency strategy should be used?", answer: "Keep tar as a normal package dependency and permit package-registry acquisition", status: "decided" },
    { phase_id: "phase-2", gate_type: "phase-2-scope-decision", question: "Should private GitHub API access use gh auth fallback?", answer: "Use GH_TOKEN, then GITHUB_TOKEN, then gh auth, then anonymous", status: "decided" }
    ,{ phase_id: "phase-2", gate_type: "phase-2-routing", question: "Continue to Phase 3: TDD Red Gate?", answer: "Continue to Phase 3: TDD Red Gate", status: "decided" }
    ,{ phase_id: "phase-3", gate_type: "phase-3-exit", question: "TDD red gate complete. Continue to Phase 4?", answer: "Continue to Phase 4", status: "decided" }
    ,{ phase_id: "phase-4", gate_type: "phase-4-exit", question: "UI mockups complete. Continue to Phase 5?", answer: "Continue to Phase 5", status: "decided" }
    ,{ phase_id: "phase-5", gate_type: "phase-5-exit", question: "Continue to specification audit?", answer: "Continue to specification audit", status: "decided" }
    ,{ phase_id: "phase-6", gate_type: "optional-phase-selection", question: "Run specification audit? (Recommended)", answer: "Yes, run audit (Recommended)", status: "decided" }
    ,{ phase_id: "phase-6", gate_type: "phase-6-audit-remediation", question: "How should Maister prove exact Git acquisition identity?", answer: "Generate a prepare-time resolved-commit manifest and enforce exact selector use in protected CI. (Recommended)", status: "decided" }
    ,{ phase_id: "phase-6", gate_type: "phase-6-audit-remediation", question: "Which repository-visibility verification policy should the specification require?", answer: "Keep the current public repository, run public E2E now, and document the private migration checklist for future activation. (Selected)", status: "decided" }
    ,{ phase_id: "phase-6", gate_type: "phase-6-audit-remediation", question: "What exact connection timing contract should GitHub transport enforce?", answer: "Use one 15-second pre-header deadline per attempt covering DNS, TCP, TLS, proxy negotiation, and response headers. (Recommended)", status: "decided" }
    ,{ phase_id: "phase-8", gate_type: "phase-8-exit", question: "Continue to verification?", answer: "Continue to verification", status: "decided" }
    ,{ phase_id: "phase-9", gate_type: "phase-9-exit", question: "TDD gate passed. Continue to Phase 10?", answer: "Continue to Phase 10", status: "decided" }
    ,{ phase_id: "phase-10", gate_type: "verification-options", question: "Which standard verifications to run?", answer: "All four recommended verifications", status: "decided" }
    ,{ phase_id: "phase-10", gate_type: "optional-phase-selection/user-docs", question: "Generate user documentation?", answer: "Yes (Recommended)", status: "decided" }
    ,{ phase_id: "phase-11", gate_type: "verification-fix-selection", question: "Which issues should I fix?", answer: "Fix all fixable issues", status: "decided" }
    ,{ phase_id: "phase-11", gate_type: "verification-rerun", question: "Re-run verification to check fixes?", answer: "Yes, re-run verification", status: "decided" }
    ,{ phase_id: "phase-11", gate_type: "verification-fix-selection", question: "Which issues should I fix?", answer: "Fix all fixable issues", status: "decided" }
    ,{ phase_id: "phase-11", gate_type: "verification-rerun", question: "Re-run verification to check fixes?", answer: "Yes, re-run verification", status: "decided" }
    ,{ phase_id: "phase-11", gate_type: "verification-fix-selection", question: "Which issues should I fix?", answer: "Fix all fixable issues", status: "decided" }
    ,{ phase_id: "phase-11", gate_type: "verification-rerun", question: "Re-run verification to check fixes?", answer: "Yes, re-run verification", status: "decided" }
    ,{ phase_id: "phase-11", gate_type: "verification-known-issues", question: "Proceed with known issues?", answer: "Proceed with known issues", status: "decided" }
    ,{ phase_id: "phase-11", gate_type: "phase-11-exit", question: "Continue to Phase 12?", answer: null, status: "pending" }
    ,{ phase_id: "phase-12", gate_type: "phase-12-exit", question: "E2E complete. Continue to Phase 13?", answer: "Continue to Phase 13", status: "decided" }
    ,{ phase_id: "phase-13", gate_type: "phase-13-exit", question: "Documentation complete. Continue to Phase 14?", answer: "Continue to Phase 14", status: "decided" }
    ,{ phase_id: "phase-14", gate_type: "final-handoff-approval", question: "Complete workflow?", answer: "Complete workflow", status: "decided" }
  ]
};
