window.MAISTER_DATA = {
  generated: "2026-07-19T19:42:03Z",
  task: {
    title: "Research first-class Pi support",
    type: "research",
    status: "completed",
    description: "Research a safe Pi target and native-agent adapter based on Pi's installed subagents extension.",
    path: ".maister/tasks/research/2026-07-19-pi-support",
    current_activity: "Research completed; final handoff approved"
  },
  characteristics: {},
  phases: [
    { id: "phase-1", name: "Research foundation", icon_hint: "analysis", status: "completed", started: "2026-07-19T12:23:32Z", completed: "2026-07-19T17:09:41Z", skip_reason: null, summary: "Research foundation complete. Pi is feasible as a generated fourth target with a private package and pi-subagents dispatch bridge; product support remains unavailable pending E1-E6 implementation.", decisions: [{ decision: "Register pi as a real fourth target with adapter pi.native.", rationale: "Alias or sidecar models would bypass closed target and evidence contracts." }, { decision: "Use pi-subagents/delegation v1 only for native dispatch.", rationale: "Maister retains role resolution and durable event ownership." }, { decision: "Add identity-aware managed_array_entries for one local package declaration.", rationale: "Owning the entire packages array would violate operator-state preservation." }, { decision: "Use a separate greenfield all-target admission gate.", rationale: "The historical parity oracle is truthful only for the three migrated targets." }], risks: ["All 28 namespaced agents still require installed-package discovery proof.", "Foreground delegation has no durable replay or same-run resume.", "managed_array_entries requires adversarial receipt/drift/rollback tests.", "The parity-release baseline currently detects an unrelated exact-native.mjs mismatch."], artifacts: [{ path: "planning/research-brief.md", label: "Research brief", html: null }, { path: "planning/research-plan.md", label: "Research plan", html: null }, { path: "planning/sources.md", label: "Source catalog", html: null }, { path: "analysis/findings/01-maister-core-contract.md", label: "Maister core contract", html: null }, { path: "analysis/findings/02-pi-host-contract.md", label: "Pi host contract", html: null }, { path: "analysis/findings/03-pi-subagents-native-runtime.md", label: "Pi subagents native runtime", html: null }, { path: "analysis/findings/04-distribution-installation.md", label: "Distribution and installation", html: null }, { path: "analysis/findings/05-compatibility-validation.md", label: "Compatibility and validation", html: null }, { path: "analysis/synthesis.md", label: "Research synthesis", html: null }, { path: "outputs/research-report.md", label: "Research report", html: "outputs/research-report.html" }], gate: { question: "Research foundation complete (initialized, planned, gathered, synthesized). Continue to brainstorming evaluation?", answer: "Continue to brainstorming evaluation" } },
    { id: "phase-2", name: "Evaluate optional phases", icon_hint: "plan", status: "completed", started: "2026-07-19T17:09:41Z", completed: "2026-07-19T17:34:14Z", skip_reason: null, summary: "Brainstorming and high-level design are enabled.", decisions: [{ decision: "Enable brainstorming and explore Pi solution alternatives.", rationale: "The synthesis contains several material integration trade-offs." }, { decision: "Generate a high-level Pi target design.", rationale: "The target introduces new runtime, projection, ownership, evidence, and admission contracts." }], risks: [], artifacts: [], gate: { question: "Would you like to generate a high-level design?", answer: "Yes, generate design" } },
    { id: "phase-3", name: "Generate solution alternatives", icon_hint: "spec", status: "completed", started: "2026-07-19T17:34:14Z", completed: "2026-07-19T18:14:20Z", skip_reason: null, summary: "Five decision areas and fifteen genuine alternatives are ready for convergence.", decisions: [{ decision: "Recommend one private generated Pi package.", rationale: "Deterministic ownership and native discovery." }, { decision: "Recommend hybrid skill, prompt, and minimal-extension projection.", rationale: "Faithful workflows with the smallest executable surface." }, { decision: "Recommend a thin pi.native adapter over public delegation v1.", rationale: "Maister retains resolver, policy, evidence, and durable events." }, { decision: "Recommend identity-aware managed_array_entries.", rationale: "Narrow ownership of one shared-settings member." }, { decision: "Recommend dual-track historical parity and greenfield admission.", rationale: "Truthful evidence for migrated and new targets." }], risks: ["Delegation v1 has no full durable resume API.", "Per-command projection mapping needs review.", "Array-entry normalization and rollback need adversarial tests."], artifacts: [{ path: "outputs/solution-exploration.md", label: "Solution exploration", html: "outputs/solution-exploration.html" }], gate: { question: "Continue to solution convergence?", answer: "Continue to solution convergence" } },
    { id: "phase-4", name: "Evaluate solution alternatives", icon_hint: "plan", status: "completed", started: "2026-07-19T18:14:20Z", completed: "2026-07-19T19:11:59Z", skip_reason: null, summary: "All five Pi architecture areas converged.", decisions: [{ decision: "Use one private generated Pi package.", rationale: "Deterministic ownership and lifecycle." }, { decision: "Use hybrid semantic projection.", rationale: "Faithful workflows with minimal executable code." }, { decision: "Use a thin direct-import adapter over pi-subagents/delegation v1.", rationale: "Direct native plugin use with Maister-owned resolver and durable events." }, { decision: "Use identity-aware managed array entries.", rationale: "Own only the Maister package membership while preserving operator state." }, { decision: "Use current-state all-target admission only.", rationale: "Only the current contract matters; historical parity is removed from the active release architecture." }], risks: ["Array-entry normalization and rollback require adversarial tests.", "Delegation v1 lacks durable same-run resume."], artifacts: [{ path: "outputs/solution-exploration.md", label: "Solution exploration", html: "outputs/solution-exploration.html" }], gate: { question: "Brainstorming complete. Continue to high-level design?", answer: "Continue to high-level design" } },
    { id: "phase-5", name: "Design high-level architecture", icon_hint: "spec", status: "completed", started: "2026-07-19T19:11:59Z", completed: "2026-07-19T19:38:04Z", skip_reason: null, summary: "Canonical Core + Generated Host Adapter design completed with eight accepted MADRs.", decisions: [{ decision: "Generate a private Pi package with hybrid semantic projection.", rationale: "Canonical behavior remains the sole source." }, { decision: "Use public pi-subagents delegation v1 with Maister-owned durable events.", rationale: "Exact native execution without reimplementation." }, { decision: "Add managed_array_entries_v1.", rationale: "Narrow transactional shared-settings ownership." }, { decision: "Use one current-state four-target admission matrix.", rationale: "Only the current product contract governs release." }], risks: ["Command mapping needs implementation review.", "Lost child processes cannot resume.", "Array-entry recovery needs fault injection.", "E5 must prove all 28 exact origins."], artifacts: [{ path: "outputs/high-level-design.md", label: "High-level design", html: "outputs/high-level-design.html" }, { path: "outputs/decision-log.md", label: "Decision log", html: "outputs/decision-log.html" }], gate: { question: "Design complete. Continue to output generation?", answer: "Continue to output generation" } },
    { id: "phase-6", name: "Summarize research and hand off", icon_hint: "done", status: "completed", started: "2026-07-19T19:38:04Z", completed: "2026-07-19T19:42:03Z", skip_reason: null, summary: "All artifacts are complete and the final protected handoff was approved.", decisions: [{ decision: "Hand off the accepted architecture to a fresh development workflow.", rationale: "The research and eight MADRs form an implementation contract." }], risks: ["Implementation must prove E1-E6 before a support claim."], artifacts: [{ path: "outputs/decision-summary.md", label: "Decision summary", html: "outputs/decision-summary.html" }], gate: { question: "Approve the final handoff and complete the workflow?", answer: "Complete workflow" } }
  ],
  verification: { status: "passed", issues: [], fixes: ["Corrected Phase 5 artifacts to satisfy the mandatory summary contract and regenerated HTML companions."], reverify_count: 1 },
  gate_history: [{ phase_id: "phase-1", gate_type: "phase-1-exit", status: "decided", selected_option: "Continue to brainstorming evaluation", final_actor: "user", decided_at: "2026-07-19T17:09:41Z" }, { phase_id: "phase-2", gate_type: "optional-phase-selection", status: "decided", selected_option: "Yes, explore alternatives", final_actor: "user", decided_at: "2026-07-19T17:14:34Z" }, { phase_id: "phase-2", gate_type: "optional-phase-selection", status: "decided", selected_option: "Yes, generate design", final_actor: "user", decided_at: "2026-07-19T17:34:14Z" }, { phase_id: "phase-3", gate_type: "phase-3-exit", status: "decided", selected_option: "Continue to solution convergence", final_actor: "user", decided_at: "2026-07-19T18:14:20Z" }, { phase_id: "phase-4", gate_type: "research-convergence", status: "decided", selected_option: "One private generated Pi package (Recommended)", final_actor: "user", decided_at: "2026-07-19T18:31:01Z" }, { phase_id: "phase-4", gate_type: "research-convergence", status: "decided", selected_option: "Hybrid semantic projection (Recommended)", final_actor: "user", decided_at: "2026-07-19T18:39:52Z" }, { phase_id: "phase-4", gate_type: "research-convergence", status: "decided", selected_option: "Thin direct-import delegation adapter (Recommended)", final_actor: "user", decided_at: "2026-07-19T18:45:09Z" }, { phase_id: "phase-4", gate_type: "research-convergence", status: "decided", selected_option: "Identity-aware managed array entries (Recommended)", final_actor: "user", decided_at: "2026-07-19T18:50:55Z" }, { phase_id: "phase-4", gate_type: "research-convergence", status: "decided", selected_option: "Need more info", final_actor: "user", decided_at: "2026-07-19T18:59:06Z" }, { phase_id: "phase-4", gate_type: "research-convergence", status: "decided", selected_option: "Current-state all-target admission only (Recommended)", final_actor: "user", decided_at: "2026-07-19T19:05:50Z" }, { phase_id: "phase-4", gate_type: "phase-4-exit", status: "decided", selected_option: "Continue to high-level design", final_actor: "user", decided_at: "2026-07-19T19:11:59Z" }, { phase_id: "phase-5", gate_type: "research-clarification", status: "decided", selected_option: "Confirm assumptions", final_actor: "user", decided_at: "2026-07-19T19:16:35Z" }, { phase_id: "phase-5", gate_type: "phase-5-exit", status: "decided", selected_option: "Continue to output generation", final_actor: "user", decided_at: "2026-07-19T19:38:04Z" }, { phase_id: "phase-6", gate_type: "final-handoff-approval", status: "decided", selected_option: "Complete workflow", final_actor: "user", decided_at: "2026-07-19T19:42:03Z" }]
};
