window.MAISTER_DATA = {
  generated: "2026-07-16T10:33:37Z",
  task: {
    title: "Implement platform-independent Maister distribution",
    type: "development",
    status: "completed",
    description: "Replace host-specific generation and duplicated testing with one portable source and install-time target selection.",
    path: ".maister/tasks/development/2026-07-14-platform-independent-plugin",
    current_activity: "Workflow completed; ready for commit and pull-request review"
  },
  characteristics: {
    has_reproducible_defect: false,
    modifies_existing_code: true,
    creates_new_entities: true,
    involves_data_operations: true,
    ui_heavy: false
  },
  phases: [
    { id: "phase-1", name: "Analyze codebase & clarify requirements", icon_hint: "analysis", status: "completed", started: "2026-07-14T16:32:58Z", completed: "2026-07-14T16:56:57Z", skip_reason: null, summary: "The repository is a build-time generated architecture: one Claude-oriented source feeds three rewrite-heavy builders and committed projections. Portable ESM runtime and transactional configuration tests are reusable foundations; overlay contracts, target-aware assembly, receipt-backed installation, and rollback are missing. The user confirmed the research-approved Codex/Cursor/Kiro-only scope and required legacy deletion before completion.", decisions: ["Treat the five byte-identical orchestrator runtime modules as the initial portable-core boundary.", "Move host-specific semantic behavior into explicit overlays instead of global prose rewrites.", "Run common behavior tests once and retain host-specific seam/evidence tests.", "Support Codex, Cursor, and Kiro CLI only; remove Claude and committed generated trees before completion."], risks: ["Current installers mutate or clear destinations before transactional validation.", "CI and docs still assume generated trees and four hosts, including Claude.", "Deleting legacy trees before parity could lose behavior hidden in Claude-native files.", "Parity and deletion criteria must be explicit before legacy removal."], artifacts: [{ path: "analysis/codebase-analysis.md", label: "Codebase analysis", html: null }, { path: "analysis/clarifications.md", label: "Phase 1 clarifications", html: null }], gate: { question: "Continue to Phase 2?", answer: "Continue to Phase 2" } },
    { id: "phase-2", name: "Analyze gaps & clarify scope", icon_hint: "analysis", status: "completed", started: "2026-07-14T16:56:57Z", completed: "2026-07-14T17:55:57Z", skip_reason: null, summary: "The repository remains organized around a Claude-oriented source, three rewrite-heavy builders, three committed generated projections, and host-specific installers. The byte-identical runtime modules and existing transactional tests provide reusable foundations, but the common overlay contract, target-aware installer lifecycle, structured evidence model, and final three-host topology are missing. This is a high-risk, high-effort migration because source ownership, installation safety, compatibility policy, CI/release behavior, and documentation change together.", decisions: ["Use minimal typed primitives rather than a full workflow DSL.", "Use one common layer with explicit Codex, Cursor, and Kiro CLI overlays and a custom installer.", "Use legacy generated trees only as a migration shadow oracle, then remove them before task completion.", "Remove Claude Code from supported targets and require a separate future host-integration task for reintroduction.", "Apply capability-sensitive compatibility: semantic boundaries fail closed and packaging-only differences may be provisional.", "Test the portable core once and retain per-host overlay, materialization, installation, and available native evidence tests."], risks: ["Semantic drift in gates, delegation, hooks, progress, and continuation can survive structural parity.", "Partial installation or settings mutation can damage user state without journaled byte-exact recovery.", "Incorrect semantic-versus-packaging classification can permit unsafe provisional compatibility.", "Removing legacy before post-release observation increases the importance of parity and failure-injection gates.", "Stale documentation and CI can continue directing users toward unsupported Claude and generated-tree workflows."], artifacts: [{ path: "analysis/gap-analysis.md", label: "Gap analysis report", html: null }], gate: { type: "routing", id: "phase-2-routing", question: "Continue to Phase 5: Technical Approach, Requirements & Specification?", options: ["Continue to Phase 5: Technical Approach, Requirements & Specification", "Pause workflow"], recommendation: "Continue to Phase 5: Technical Approach, Requirements & Specification", answer: "Continue to Phase 5: Technical Approach, Requirements & Specification", status: "decided" } },
    { id: "phase-3", name: "Write failing test (TDD Red)", icon_hint: "verify", status: "skipped", started: null, completed: "2026-07-14T17:55:57Z", skip_reason: "Skipped by routing: the task is not defect-driven and the workflow routes directly to requirements and specification.", summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-4", name: "Generate UI mockups", icon_hint: "spec", status: "skipped", started: null, completed: "2026-07-14T17:55:57Z", skip_reason: "Skipped by routing: gap analysis found no UI-heavy scope.", summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-5", name: "Gather requirements & create specification", icon_hint: "spec", status: "completed", started: "2026-07-14T17:55:57Z", completed: "2026-07-14T18:19:59Z", skip_reason: null, summary: "The specification defines a portable common source, explicit Codex/Cursor/Kiro CLI overlays, and a shared target-aware installer with immutable provenance, staged validation, journaled receipts, hybrid settings ownership, capability-sensitive evidence, rollback, and legacy deletion criteria. It also aligns core-once/per-host testing and all documentation, standards, CI, and release paths with the new topology.", decisions: ["Use a portable common layer plus explicit host overlays because native layouts remain host-specific while behavior should be owned once.", "Treat the installer as a transaction manager because user state and settings require staged validation, receipts, recovery, and rollback.", "Use capability-sensitive compatibility because semantic boundaries must fail closed while packaging-only differences can be provisional.", "Delete Claude and generated trees only after zero-unresolved-difference shadow parity and failure-injection evidence."], risks: ["Native E5/E6 evidence may remain unavailable for Cursor and Kiro.", "Shared settings and shell files can be damaged without journaled ownership and exact rollback.", "Textual parity can conceal semantic drift in gates, delegation, hooks, and continuation.", "Legacy deletion removes the current rollback oracle and depends on complete parity evidence."], artifacts: [{ path: "analysis/requirements.md", label: "Requirements", html: null }, { path: "analysis/technical-clarifications.md", label: "Technical clarifications", html: null }, { path: "implementation/spec.md", label: "Specification", html: "implementation/spec.html" }], gate: { type: "phase-exit", id: "phase-5-exit", question: "Continue to specification audit?", options: ["Continue to specification audit", "Pause workflow"], recommendation: "Continue to specification audit", answer: "Continue to specification audit", status: "decided" } },
    { id: "phase-6", name: "Audit specification", icon_hint: "verify", status: "completed", started: "2026-07-14T18:19:59Z", completed: "2026-07-14T18:36:21Z", skip_reason: null, summary: "The specification is Mostly Compliant as a pre-implementation contract: all 17 requirements map to the research decisions, current-state gaps, and migration exit criteria. There are no critical or high-severity specification defects; two medium clarifications remain around the exact installer/receipt contract and the field-level overlay schema.", decisions: ["Treat current legacy implementation gaps as expected pre-implementation state because the specification explicitly covers migration and deletion criteria.", "Freeze exact installer/receipt and overlay schema contracts in the implementation plan before implementation approval."], risks: ["Native E5/E6 evidence may remain unavailable for Cursor and Kiro.", "Shared settings and shell files require exact journaled rollback.", "Textual parity can conceal semantic drift."], artifacts: [{ path: "verification/spec-audit.md", label: "Specification audit", html: null }], gate: { type: "phase-exit", id: "phase-6-exit", question: "Continue to implementation planning?", options: ["Continue to implementation planning", "Pause workflow"], recommendation: "Continue to implementation planning", answer: "Continue to implementation planning", status: "decided" } },
    { id: "phase-7", name: "Plan implementation", icon_hint: "plan", status: "completed", started: "2026-07-14T18:36:21Z", completed: "2026-07-14T18:54:09Z", skip_reason: null, summary: "The plan organizes the migration into four serialized implementation groups plus a focused test-review group. It freezes overlay v1 and the installer CLI/error/receipt/journal contracts, preserves legacy outputs until parity and failure-injection evidence pass, and caps the feature suite at 34 tests.", decisions: ["Keep plugins/maister as the single common source and represent host differences in strict versioned overlays.", "Serialize overlay, materializer, installer, and legacy-removal groups because each freezes an interface consumed by the next.", "Use one Node ESM lifecycle command with stable machine-readable errors, receipt v1, and journal v1.", "Delete Claude support, old builders, and generated trees only after zero-unresolved parity and exact recovery evidence."], risks: ["Cursor and Kiro E5/E6 may remain unavailable and must never be promoted to passed.", "Shared settings require journaled multi-file recovery in addition to atomic managed-tree replacement.", "A real immutable GitHub smoke probe depends on release-environment network availability.", "No performance threshold is introduced in this migration."], artifacts: [{ path: "implementation/implementation-plan.md", label: "Implementation plan", html: "implementation/implementation-plan.html" }], gate: { type: "phase-exit", id: "phase-7-exit", question: "Continue to implementation approval?", options: ["Continue to implementation approval", "Pause workflow"], recommendation: "Continue to implementation approval", answer: "Continue to implementation approval", status: "decided" } },
    { id: "phase-8", name: "Execute implementation", icon_hint: "code", status: "completed", started: "2026-07-14T19:08:52Z", completed: "2026-07-14T22:12:26Z", skip_reason: null, summary: "All five approved groups are complete. The feature suite passes 34/34, all targets materialize, parity has zero unresolved differences, and final topology is clean.", decisions: [], risks: [], artifacts: [], gate: { question: "Continue to verification?", answer: "Continue to verification" } },
    { id: "phase-9", name: "Verify test passes (TDD Green)", icon_hint: "verify", status: "skipped", started: null, completed: "2026-07-15T12:40:53Z", skip_reason: "Phase 3 TDD Red was not executed because the task was not defect-driven.", summary: null, decisions: [], risks: [], artifacts: [], gate: null },
    { id: "phase-10", name: "Prompt verification options", icon_hint: "verify", status: "completed", started: "2026-07-15T12:40:53Z", completed: "2026-07-15T12:47:27Z", skip_reason: null, summary: "All four standard verification tracks and user documentation are enabled; E2E browser verification is skipped.", decisions: [], risks: [], artifacts: [], gate: { question: "Generate user documentation?", answer: "Yes (Recommended)" } },
    { id: "phase-11", name: "Verify implementation & resolve issues", icon_hint: "verify", status: "completed", started: "2026-07-15T18:46:53Z", completed: "2026-07-15T22:30:35Z", skip_reason: null, summary: "Final verification passes all 39 plan steps and 17 requirements with 114/114 authoritative tests, 20/20 focused evidence/topology checks, make validate, package lifecycle 4/4, and clean strict parity for all three targets with zero unresolved differences. Both former P1s, stale test contracts, and the topology contract issue are resolved with zero regressions.", decisions: ["Carry one immutable source binding through overlay selection, materialization, evidence, and receipts.", "Keep supported-target ownership in the central Node registry.", "Use tracked plus non-ignored untracked Git candidates for repository topology while retaining raw fixture traversal.", "Separate the passed implementation verdict from exact-tag publication controls."], risks: ["The exact tag commit must repeat the complete clean release sequence before publication.", "Native E6 remains unavailable where no reviewed host scenario exists.", "Unsigned provenance and cooperative-writer limits remain documented release boundaries."], artifacts: [{ path: "verification/implementation-verification.md", label: "Implementation verification", html: "verification/implementation-verification.html" }, { path: "verification/test-suite-results.md", label: "Test suite results", html: null }, { path: "verification/code-review-report.md", label: "Code review", html: null }, { path: "verification/production-readiness-report.md", label: "Production readiness", html: null }, { path: "verification/reality-check.md", label: "Reality assessment", html: null }], gate: { question: "Continue to Phase 12?", answer: "Continue to Phase 12" } },
    { id: "phase-12", name: "Run E2E tests", icon_hint: "verify", status: "skipped", started: null, completed: "2026-07-16T08:13:13Z", skip_reason: "E2E verification disabled by the selected Phase 10 verification options.", summary: "No browser verifier was dispatched because e2e_enabled is false.", decisions: ["Honor the configured E2E skip and preserve Phase 13 documentation as enabled."], risks: [], artifacts: [], gate: { question: "E2E complete. Continue to Phase 13?", answer: "Continue to Phase 13" } },
    { id: "phase-13", name: "Generate user documentation", icon_hint: "docs", status: "completed", started: "2026-07-16T08:30:49Z", completed: "2026-07-16T08:40:06Z", skip_reason: null, summary: "The CLI-focused user guide covers all supported targets and lifecycle commands, source forms, safety boundaries, result codes, evidence limitations, and troubleshooting. Eight command shapes, all links, all anchors, Markdown structure, and diff hygiene pass.", decisions: ["Omit screenshots because the product is CLI-only and Phase 12 was skipped.", "Treat copy-paste CLI commands as user actions rather than developer code.", "Validate every documented command and flag against the live parser and implementation."], risks: ["Native E5/E6 evidence remains unavailable where no reviewed host scenario exists."], artifacts: [{ path: "documentation/user-guide.md", label: "User guide", html: null }], gate: { question: "Documentation complete. Continue to Phase 14?", answer: "Continue to Phase 14" } },
    { id: "phase-14", name: "Finalize workflow", icon_hint: "done", status: "completed", started: "2026-07-16T09:17:19Z", completed: "2026-07-16T10:33:37Z", skip_reason: null, summary: "The canonical 31-record decision ledger and self-contained HTML companion are complete. The user approved the protected final handoff and the workflow completion checkpoint is durable.", decisions: ["Generate final summaries only from canonical gate history.", "Preserve every decision option, rationale, confidence, model/retry/arbitration field, override, and idempotency key.", "Require and persist protected final-handoff approval before task completion."], risks: ["Production publication remains conditional on the exact clean tag workflow."], artifacts: [{ path: "outputs/decision-summary.md", label: "Decision summary", html: "outputs/decision-summary.html" }], gate: { question: "Complete workflow or keep it open?", answer: "Complete workflow" } }
  ],
  verification: { status: "passed", issues: [], fixes: ["Phase 11 fix iteration 1 completed; 60/60 focused tests pass", "Phase 11 fix iteration 2 completed; 91/91 suite and release checks pass", "Phase 11 fix iteration 3 completed; 109/109 suite, make validate, package lifecycle, and diagnostic parity pass", "Iteration 3 independently resolved or downgraded persisted-state reads, final-byte mutation checks, overlay fallback, direct E3, parser grammar, and validated release inputs", "Resumed iteration 1 carries one immutable source binding through lifecycle and materialization and rejects A/B mismatch before state mutation", "Resumed iteration 1 removes Make target interpolation and rejects SUPPORTED_TARGETS overrides before evaluation", "Resumed iteration 2 updates the topology contract for Node registry ownership", "Resumed iteration 2 supplies immutable Git identity to the overlay-negative fixture", "Resumed iteration 3 centralizes Git-aware repository topology and passes 114/114 tests plus clean strict parity 3/3"], reverify_count: 3 },
  gate_history: [
    { phase_id: "phase-1", gate_type: "phase-1-clarification", question: "I assume the implementation scope is Codex, Cursor, and Kiro CLI only, with Claude and committed generated trees removed before completion. Is that correct?", answer: "Confirm assumptions" },
    { phase_id: "phase-1", gate_type: "phase-1-exit", question: "Continue to Phase 2?", answer: "Continue to Phase 2" },
    { phase_id: "phase-2", gate_type: "phase-2-decision-host-contract-closure", question: "Which host-contract closure policy should the implementation adopt?", answer: "Contract-first overlay v1 with E1/E2/E4 for every host and E5/E6 when runtime exists" },
    { phase_id: "phase-2", gate_type: "phase-2-decision-settings-ownership", question: "Which settings and shell-configuration ownership contract should the implementation adopt?", answer: "Hybrid whole_file and managed_keys ownership with journal, backup, drift detection, and exact rollback" },
    { phase_id: "phase-2", gate_type: "phase-2-decision-native-evidence-policy", question: "Which minimum release-evidence policy should apply to hosts without native runtime?", answer: "Require E1-E4 and shared-core E3; record E5/E6 as unavailable, never pass" },
    { phase_id: "phase-2", gate_type: "phase-2-decision-evidence-freshness", question: "Which evidence freshness policy should the implementation adopt?", answer: "Per-capability expiry with host, version, scenario, and timestamp renewal" },
    { phase_id: "phase-2", gate_type: "phase-2-decision-documentation-boundary", question: "Which documentation and release migration boundary should the implementation adopt?", answer: "Update all affected documentation, standards, Make/CI/release paths, and support matrices in this task" },
    { phase_id: "phase-2", gate_type: "phase-2-routing", question: "Continue to Phase 5: Technical Approach, Requirements & Specification?", answer: "Continue to Phase 5: Technical Approach, Requirements & Specification" },
    { phase_id: "phase-5", gate_type: "phase-5-exit", question: "Continue to specification audit?", answer: "Continue to specification audit" },
    { phase_id: "phase-6", gate_type: "phase-6-exit", question: "Continue to implementation planning?", answer: "Continue to implementation planning" },
    { phase_id: "phase-7", gate_type: "phase-7-exit", question: "Continue to implementation approval?", answer: "Continue to implementation approval" },
    { phase_id: "phase-7", gate_type: "implementation-approval", question: "Approve this complete implementation scope?", answer: "Approve complete implementation scope" },
    { phase_id: "phase-8", gate_type: "group-failure-recovery", question: "Group 4 implementation failed: materialization parity gate is red for Codex, Cursor, and Kiro CLI inventory/vocabulary contracts. How to proceed?", answer: "Try suggested fix" },
    { phase_id: "phase-8", gate_type: "group-failure-recovery", question: "Group 4 implementation failed: materialization is green but real shadow parity still has 573 unresolved differences across Codex, Cursor, and Kiro CLI. How to proceed?", answer: "Try suggested fix" },
    { phase_id: "phase-8", gate_type: "group-failure-recovery", question: "Group 1 implementation failed: delegated agent timed out without a report. How to proceed?", answer: "Try suggested fix" }
    ,{ phase_id: "phase-8", gate_type: "phase-8-exit", question: "Continue to verification?", answer: "Continue to verification" }
    ,{ phase_id: "phase-10", gate_type: "verification-options", question: "Which standard verifications to run?", answer: "All recommended standard verifications" }
    ,{ phase_id: "phase-10", gate_type: "optional-phase-selection/e2e", question: "Enable E2E browser verification?", answer: "No, skip" }
    ,{ phase_id: "phase-10", gate_type: "optional-phase-selection/user-docs", question: "Generate user documentation?", answer: "Yes (Recommended)" }
    ,{ phase_id: "phase-11", gate_type: "verification-fix-selection", question: "Which issues should I fix?", answer: "Fix all fixable issues" }
    ,{ phase_id: "phase-11", gate_type: "verification-rerun", question: "Re-run verification to check fixes?", answer: "Yes, re-run verification" }
    ,{ phase_id: "phase-11", gate_type: "verification-fix-selection", question: "Which issues should I fix?", answer: "Fix all fixable issues" }
    ,{ phase_id: "phase-11", gate_type: "verification-rerun", question: "Re-run verification to check fixes?", answer: "Yes, re-run verification" }
    ,{ phase_id: "phase-11", gate_type: "verification-rerun", question: "Re-run verification to check fixes?", answer: "Yes, re-run verification" }
    ,{ phase_id: "phase-11", gate_type: "verification-fix-selection", question: "Which issues should I fix?", answer: "Fix all fixable issues" }
    ,{ phase_id: "phase-11", gate_type: "unresolved-critical", question: "Proceed with known issues?", answer: "Stop workflow" }
    ,{ phase_id: "phase-11", gate_type: "verification-fix-selection", question: "Which issues should I fix?", answer: "Fix all fixable issues" }
    ,{ phase_id: "phase-11", gate_type: "phase-11-exit", question: "Continue to Phase 12?", answer: "Continue to Phase 12" }
    ,{ phase_id: "phase-12", gate_type: "phase-12-exit", question: "E2E complete. Continue to Phase 13?", answer: "Continue to Phase 13" }
    ,{ phase_id: "phase-13", gate_type: "phase-13-exit", question: "Documentation complete. Continue to Phase 14?", answer: "Continue to Phase 14" }
    ,{ phase_id: "phase-14", gate_type: "final-handoff-approval", question: "Complete workflow or keep it open?", answer: "Complete workflow" }
  ]
};
